# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Martin Filliau
tagline:          'Software developer'
description:      'Software developer'
url:              https://martin.filliau.com

author:
  name:           'Martin Filliau'
  url:            https://martin.filliau.com

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/poole/hyde
